"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Symbolic constant s for various Python Language tokens.
 */
var Tokens;
(function (Tokens) {
    Tokens[Tokens["T_ENDMARKER"] = 0] = "T_ENDMARKER";
    Tokens[Tokens["T_NAME"] = 1] = "T_NAME";
    Tokens[Tokens["T_NUMBER"] = 2] = "T_NUMBER";
    Tokens[Tokens["T_STRING"] = 3] = "T_STRING";
    Tokens[Tokens["T_NEWLINE"] = 4] = "T_NEWLINE";
    Tokens[Tokens["T_INDENT"] = 5] = "T_INDENT";
    Tokens[Tokens["T_DEDENT"] = 6] = "T_DEDENT";
    Tokens[Tokens["T_LPAR"] = 7] = "T_LPAR";
    Tokens[Tokens["T_RPAR"] = 8] = "T_RPAR";
    Tokens[Tokens["T_LSQB"] = 9] = "T_LSQB";
    Tokens[Tokens["T_RSQB"] = 10] = "T_RSQB";
    Tokens[Tokens["T_COLON"] = 11] = "T_COLON";
    Tokens[Tokens["T_COMMA"] = 12] = "T_COMMA";
    Tokens[Tokens["T_SEMI"] = 13] = "T_SEMI";
    Tokens[Tokens["T_PLUS"] = 14] = "T_PLUS";
    Tokens[Tokens["T_MINUS"] = 15] = "T_MINUS";
    Tokens[Tokens["T_STAR"] = 16] = "T_STAR";
    Tokens[Tokens["T_SLASH"] = 17] = "T_SLASH";
    Tokens[Tokens["T_VBAR"] = 18] = "T_VBAR";
    Tokens[Tokens["T_AMPER"] = 19] = "T_AMPER";
    Tokens[Tokens["T_LESS"] = 20] = "T_LESS";
    Tokens[Tokens["T_GREATER"] = 21] = "T_GREATER";
    Tokens[Tokens["T_EQUAL"] = 22] = "T_EQUAL";
    Tokens[Tokens["T_DOT"] = 23] = "T_DOT";
    Tokens[Tokens["T_PERCENT"] = 24] = "T_PERCENT";
    Tokens[Tokens["T_BACKQUOTE"] = 25] = "T_BACKQUOTE";
    Tokens[Tokens["T_LBRACE"] = 26] = "T_LBRACE";
    Tokens[Tokens["T_RBRACE"] = 27] = "T_RBRACE";
    Tokens[Tokens["T_EQEQUAL"] = 28] = "T_EQEQUAL";
    Tokens[Tokens["T_NOTEQUAL"] = 29] = "T_NOTEQUAL";
    Tokens[Tokens["T_LESSEQUAL"] = 30] = "T_LESSEQUAL";
    Tokens[Tokens["T_GREATEREQUAL"] = 31] = "T_GREATEREQUAL";
    Tokens[Tokens["T_TILDE"] = 32] = "T_TILDE";
    Tokens[Tokens["T_CIRCUMFLEX"] = 33] = "T_CIRCUMFLEX";
    Tokens[Tokens["T_LEFTSHIFT"] = 34] = "T_LEFTSHIFT";
    Tokens[Tokens["T_RIGHTSHIFT"] = 35] = "T_RIGHTSHIFT";
    Tokens[Tokens["T_DOUBLESTAR"] = 36] = "T_DOUBLESTAR";
    Tokens[Tokens["T_PLUSEQUAL"] = 37] = "T_PLUSEQUAL";
    Tokens[Tokens["T_MINEQUAL"] = 38] = "T_MINEQUAL";
    Tokens[Tokens["T_STAREQUAL"] = 39] = "T_STAREQUAL";
    Tokens[Tokens["T_SLASHEQUAL"] = 40] = "T_SLASHEQUAL";
    Tokens[Tokens["T_PERCENTEQUAL"] = 41] = "T_PERCENTEQUAL";
    Tokens[Tokens["T_AMPEREQUAL"] = 42] = "T_AMPEREQUAL";
    Tokens[Tokens["T_VBAREQUAL"] = 43] = "T_VBAREQUAL";
    Tokens[Tokens["T_CIRCUMFLEXEQUAL"] = 44] = "T_CIRCUMFLEXEQUAL";
    Tokens[Tokens["T_LEFTSHIFTEQUAL"] = 45] = "T_LEFTSHIFTEQUAL";
    Tokens[Tokens["T_RIGHTSHIFTEQUAL"] = 46] = "T_RIGHTSHIFTEQUAL";
    Tokens[Tokens["T_DOUBLESTAREQUAL"] = 47] = "T_DOUBLESTAREQUAL";
    Tokens[Tokens["T_DOUBLESLASH"] = 48] = "T_DOUBLESLASH";
    Tokens[Tokens["T_DOUBLESLASHEQUAL"] = 49] = "T_DOUBLESLASHEQUAL";
    Tokens[Tokens["T_AT"] = 50] = "T_AT";
    Tokens[Tokens["T_OP"] = 51] = "T_OP";
    Tokens[Tokens["T_COMMENT"] = 52] = "T_COMMENT";
    Tokens[Tokens["T_NL"] = 53] = "T_NL";
    Tokens[Tokens["T_RARROW"] = 54] = "T_RARROW";
    Tokens[Tokens["T_ERRORTOKEN"] = 55] = "T_ERRORTOKEN";
    Tokens[Tokens["T_N_TOKENS"] = 56] = "T_N_TOKENS";
    Tokens[Tokens["T_NT_OFFSET"] = 256] = "T_NT_OFFSET";
})(Tokens = exports.Tokens || (exports.Tokens = {}));
